version: '1.0'

services:
  app:
    build: .
    ports:
      - "8000:80"
    networks:
      - careerlens-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - careerlens-network

volumes:
  mongodb_data:

networks:
  careerlens-network:
    name: careerlens-network
